class_name World
extends RefCounted
## Endless procedural terrain, a pure function of (seed, x, y) in world tiles. Only integer hashing and + - * / are used
## (no sin/pow/engine noise), so every machine in a multiplayer game derives bit-identical land from the seed alone.
## Tiles are generated by chunk and cached; `csize` is a parameter only so tests can prove chunk borders leave no seam.

enum K { SEA, RIVER, SAND, PLAIN, FOREST, HILL, ROCK }

const SEA_LEVEL := 0.36
const PAD := 3  # river lines need the field one tile past the chunk, then a one-tile dilation
const MAX_CHUNKS := 512

var seed := 0
var csize := 32
var _last := Vector2i(1 << 30, 1 << 30)
var _cache := {}  # Vector2i -> {"k": PackedByteArray, "o": PackedByteArray}


func _init(sd := 0, chunk := 32) -> void:
	seed = sd
	csize = chunk


static func _h(x: int, y: int, s: int) -> float:
	var n := (x * 374761393 + y * 668265263 + s * 1274126177) & 0xFFFFFFFF
	n = ((n ^ (n >> 13)) * 1274126177) & 0xFFFFFFFF
	n = n ^ (n >> 16)
	return float(n & 0xFFFFFF) / 16777216.0


static func _vn(x: float, y: float, s: int) -> float:
	var xi := floori(x)
	var yi := floori(y)
	var fx := x - xi
	var fy := y - yi
	fx = fx * fx * (3.0 - 2.0 * fx)
	fy = fy * fy * (3.0 - 2.0 * fy)
	var a := _h(xi, yi, s)
	var b := _h(xi + 1, yi, s)
	var c := _h(xi, yi + 1, s)
	var d := _h(xi + 1, yi + 1, s)
	return (a + (b - a) * fx) + ((c + (d - c) * fx) - (a + (b - a) * fx)) * fy


static func _fbm(x: float, y: float, s: int, oct: int) -> float:
	var sum := 0.0
	var amp := 1.0
	var tot := 0.0
	var f := 1.0
	for o in oct:
		sum += _vn(x * f, y * f, s + o * 7919) * amp
		tot += amp
		amp *= 0.5
		f *= 2.0
	return sum / tot


const STEP := 4  # slow fields are sampled every STEP tiles and interpolated, 16x cheaper; chunk sizes must be multiples of it
enum F { ELEV, MOIST, RIVER }


## Field value at a lattice point (world tile gx*STEP, gy*STEP). Rivers follow the 0.5 level line of RIVER.
func _lat(f: int, gx: int, gy: int) -> float:
	var x := gx * STEP
	var y := gy * STEP
	match f:
		F.ELEV:
			return _fbm(x / 110.0, y / 110.0, seed, 4)
		F.MOIST:
			return _fbm(x / 90.0, y / 90.0, seed + 101, 3)
	return _fbm(x / 90.0, y / 90.0, seed + 211, 2)


## Interpolated field over the w*h tiles starting at (x0, y0), row-major.
func _grid(f: int, x0: int, y0: int, w: int, h: int) -> PackedFloat64Array:
	var gx0 := floori(float(x0) / STEP)
	var gy0 := floori(float(y0) / STEP)
	var lw := floori(float(x0 + w - 1) / STEP) + 2 - gx0
	var lh := floori(float(y0 + h - 1) / STEP) + 2 - gy0
	var lat := PackedFloat64Array()
	lat.resize(lw * lh)
	for j in lh:
		for i in lw:
			lat[j * lw + i] = _lat(f, gx0 + i, gy0 + j)
	var out := PackedFloat64Array()
	out.resize(w * h)
	for j in h:
		var y := y0 + j
		var gy := floori(float(y) / STEP)
		var ty := float(y - gy * STEP) / STEP
		var row := (gy - gy0) * lw
		for i in w:
			var x := x0 + i
			var gx := floori(float(x) / STEP)
			var tx := float(x - gx * STEP) / STEP
			var k := row + gx - gx0
			var a := lat[k] + (lat[k + 1] - lat[k]) * tx
			var b := lat[k + lw] + (lat[k + lw + 1] - lat[k + lw]) * tx
			out[j * w + i] = a + (b - a) * ty
	return out


func elevation(x: int, y: int) -> float:
	return _grid(F.ELEV, x, y, 1, 1)[0]


func _gen(cx: int, cy: int) -> Dictionary:
	var n := csize + 2 * PAD
	var rf := _grid(F.RIVER, cx * csize - PAD, cy * csize - PAD, n, n)
	var side := PackedByteArray()
	side.resize(n * n)
	for q in n * n:
		side[q] = 1 if rf[q] >= 0.5 else 0
	var line := PackedByteArray()  # cells where the level line crosses toward +x or +y
	line.resize(n * n)
	for j in n - 1:
		for i in n - 1:
			if side[j * n + i] != side[j * n + i + 1] or side[j * n + i] != side[(j + 1) * n + i]:
				line[j * n + i] = 1
	var k := PackedByteArray()
	k.resize(csize * csize)
	var o := PackedByteArray()
	o.resize(csize * csize)
	var ef := _grid(F.ELEV, cx * csize, cy * csize, csize, csize)
	var mf := _grid(F.MOIST, cx * csize, cy * csize, csize, csize)
	for j in csize:
		for i in csize:
			var x := cx * csize + i
			var y := cy * csize + j
			var e := ef[j * csize + i]
			var m := mf[j * csize + i]
			var kind: int
			if e < SEA_LEVEL:
				kind = K.SEA
			else:
				var river := false
				if e > SEA_LEVEL + 0.02 and e < 0.64:  # springs rise at the foot of the hills
					for dj in range(-1, 2):
						for di in range(-1, 2):
							if line[(j + PAD + dj) * n + i + PAD + di] == 1:
								river = true
				if river:
					kind = K.RIVER
				elif e < SEA_LEVEL + 0.03:
					kind = K.SAND
				elif e > 0.72:
					kind = K.ROCK
				elif e > 0.64:
					kind = K.HILL
				elif m > 0.58:
					kind = K.FOREST
				else:
					kind = K.PLAIN
			k[j * csize + i] = kind
			if kind >= K.PLAIN:
				var v := _vn(x / 5.0, y / 5.0, seed + 307)
				var need := 0.90 if kind < K.HILL else 0.80
				if v > need:
					o[j * csize + i] = 3 if v > need + 0.06 else (2 if v > need + 0.03 else 1)
	return {"k": k, "o": o}


func _chunk(x: int, y: int) -> Dictionary:
	var cp := Vector2i(floori(float(x) / csize), floori(float(y) / csize))
	if cp != _last:  # LRU: a Dictionary keeps insertion order, so re-insert on use and evict the first key
		_last = cp
		var c: Variant = _cache.get(cp)
		if c == null:
			if _cache.size() >= MAX_CHUNKS:
				_cache.erase(_cache.keys()[0])
			c = _gen(cp.x, cp.y)
		else:
			_cache.erase(cp)
		_cache[cp] = c
	return _cache[cp]


## Raw chunk (cx, cy): {"k": kinds, "o": ore}, csize * csize bytes each.
func chunk(cx: int, cy: int) -> Dictionary:
	return _chunk(cx * csize, cy * csize)


func _at(x: int, y: int) -> int:
	return posmod(y, csize) * csize + posmod(x, csize)


func kind(x: int, y: int) -> int:
	return _chunk(x, y)["k"][_at(x, y)]


func ore(x: int, y: int) -> int:
	return _chunk(x, y)["o"][_at(x, y)]


## Rivers, lakes and the sea: nothing is built here, only road bridges (and wires/pipes) cross.
func is_water(x: int, y: int) -> bool:
	var k := kind(x, y)
	return k == K.SEA or k == K.RIVER


## Kinds and ore for the w*h tiles at (x0, y0), row-major: {"k": PackedByteArray, "o": PackedByteArray}.
func region(x0: int, y0: int, w: int, h: int) -> Dictionary:
	var k := PackedByteArray()
	k.resize(w * h)
	var o := PackedByteArray()
	o.resize(w * h)
	for j in h:
		var y := y0 + j
		var i := 0
		while i < w:
			var x := x0 + i
			var ch := _chunk(x, y)
			var at := posmod(y, csize) * csize + posmod(x, csize)
			var run := mini(w - i, csize - posmod(x, csize))
			for r in run:
				k[j * w + i + r] = ch["k"][at + r]
				o[j * w + i + r] = ch["o"][at + r]
			i += run
	return {"k": k, "o": o}
