#!/usr/bin/env python3
"""Generates the reference pages of docs/wiki/ from the game's data tables.
Usage: python3 scripts/gen_wiki.py [--check]   (GODOT=/path/to/godot, default `godot`)
--check regenerates into a temp dir and fails if docs/wiki/ differs (CI)."""
import json, os, subprocess, sys, tempfile, pathlib, filecmp

root = pathlib.Path(__file__).resolve().parent.parent
GEN = "<!-- GENERATED by scripts/gen_wiki.py from the game data. Do not edit by hand: change the data in client/scripts and rerun it. -->\n"


def dump():
    out = pathlib.Path(tempfile.mkdtemp()) / "wd.json"
    subprocess.run([os.environ.get("GODOT", "godot"), "--headless", "--path", str(root / "client"), "-s",
                    "tools/dump_wiki.gd", "--", str(out)], check=True, capture_output=True, timeout=180)
    return json.loads(out.read_text())


def pct(x):
    return f"{round(x * 100):d}%"


def num(x):
    return f"{x:g}" if isinstance(x, (int, float)) else str(x)


def mods(m):
    return ", ".join(f"`{k}` {num(v)}" for k, v in m.items()) or "none"


def anchor(s):
    return "".join(c if c.isalnum() else "-" for c in s.lower()).strip("-")


def buildings(d):
    ids = d["ids"]
    met = d["metrics"]
    tr = d["tribes"]
    L = [GEN, "# Buildings and tiles\n",
         f"{len(d['defs'])} placeable things in {len(d['cats'])} categories. `unlock` is the population (peak) at which the Build menu offers it. "
         "Costs are coins; `upkeep` is coins per second before the town-size and policy multipliers (see [Economy](economy.md)).\n",
         "How to read an entry: **Radius** is the service reach in tiles (Manhattan diamond); **Provides** lists the city-stat coverage it adds (see [City stats](stats.md)); "
         "**Output** is the network supply it adds (power, water, sewage units); **Jobs** is staff; **Pollution** is `[radius, strength]`; "
         "**Tourism** is visitor income strength; **Visited** means citizens walk there as a leisure destination; **Grant** is a free income (coins per second, scaled by `RATE`).\n"]
    for cid, cname in d["cats"]:
        items = [(int(k), v) for k, v in d["defs"].items() if v["cat"] == cid]
        L.append(f"## {cname}\n")
        L.append("| Building | Cost | Upkeep | Unlock | Kind |\n|---|---|---|---|---|")
        for k, v in items:
            L.append(f"| [{v['n']}](#{anchor(v['n'])}) | {num(v['cost'])} | {num(v['up'])} | {num(v['unlock'])} | {v['kind']} |")
        L.append("")
        for k, v in items:
            L.append(f"### {v['n']}\n")
            L.append(f"{v['desc']}\n")
            rows = [("Id", f"`{ids[str(k)]}`"), ("Cost / upkeep", f"{num(v['cost'])} / {num(v['up'])} per s"),
                    ("Unlocks at", f"{num(v['unlock'])} population"), ("Kind", v["kind"])]
            if v.get("sector"):
                rows.append(("Zone sector", v["sector"]))
            if v["kind"] == "zone":
                rows.append(("Residents per level", num(v.get("home", 0))))
                rows.append(("Jobs per level", num(v.get("jobs", 0))))
                rows.append(("Max level", num(v.get("max", 1))))
                if "tier" in v:
                    rows.append(("Tax tier", f"x{num(v['tier'])}"))
            if "r" in v and v["r"]:
                rows.append(("Radius", f"{num(v['r'])} tiles"))
            if v.get("prov"):
                rows.append(("Provides", ", ".join(f"{met[m]['n']} {pct(s)}" if m in met else f"{m} {pct(s)}" for m, s in v["prov"].items())))
            if v.get("out"):
                rows.append(("Output", ", ".join(f"{n} {num(a)}" for n, a in v["out"].items())))
            if v["kind"] == "svc" and "jobs" in v:
                rows.append(("Jobs", num(v["jobs"])))
            if v.get("poll"):
                rows.append(("Pollution", f"radius {num(v['poll'][0])}, strength {num(v['poll'][1])}"))
            if v.get("tour"):
                rows.append(("Tourism", num(v["tour"])))
            if v.get("spot"):
                rows.append(("Visited", "citizens walk here for leisure"))
            if v.get("grant"):
                rows.append(("Grant", f"{num(v['grant'])} x RATE coins per second"))
            if v.get("crime"):
                rows.append(("Local crime", f"+{num(v['crime'])}"))
            if v.get("faction"):
                rows.append(("Pleases tribe", tr[v["faction"]]["n"]))
            if v.get("chain"):
                rows.append(("Production chain", v["chain"]))
            if v.get("water"):
                rows.append(("Placement", "must touch water"))
            if v.get("layer"):
                rows.append(("Network layer", v["layer"]))
            rows.append(("Map colour / letter", f"`{v['col']}` / `{v['g'] or '-'}`"))
            L.append("| | |\n|---|---|")
            L += [f"| {a} | {b} |" for a, b in rows]
            L.append(f"\n*Tip:* {v['tip']}\n" if v.get("tip") else "")
    return "\n".join(L)


def stats(d):
    L = [GEN, "# City stats (coverage metrics)\n",
         "Each stat is the share of homes covered by the services that provide it (0-100%). A `need` stat lowers mood by `weight` x the uncovered share once the town is big enough "
         "to care (`need pop`); a `bonus` stat raises mood or income; `safety` has no direct mood effect.\n",
         "| Stat | Kind | Mood weight | Provided by |\n|---|---|---|---|"]
    by = {}
    for k, v in d["defs"].items():
        for m in v.get("prov", {}):
            by.setdefault(m, []).append(v["n"])
        for m in v.get("out", {}):
            by.setdefault(m, []).append(v["n"])
    for k, v in d["metrics"].items():
        L.append(f"| [{v['n']}](#{anchor(v['n'])}) | {v['kind']} | {num(v['w'])} | {', '.join(by.get(k, [])) or '-'} |")
    L.append("")
    for k, v in d["metrics"].items():
        L.append(f"## {v['n']}\n\nKey `{k}`. {v['txt']}\n\n> \"{v['say']}\"\n")
        if by.get(k):
            L.append("Provided by: " + ", ".join(by[k]) + ".\n")
    return "\n".join(L)


def policies(d):
    L = [GEN, "# Policies\n", "Toggle in the Policy tab. `upkeep` is coins per second (negative = saves coins). `mods` are the numeric modifiers the policy adds (see [Economy](economy.md) for what each modifier does).\n",
         "| Policy | Upkeep | Modifiers |\n|---|---|---|"]
    for k, v in d["policies"].items():
        L.append(f"| [{v['n']}](#{anchor(v['n'])}) | {num(v['up'])} | {mods(v['mods'])} |")
    L.append("")
    for k, v in d["policies"].items():
        L.append(f"## {v['n']}\n\nKey `{k}`. {v['desc']}\n\n- Upkeep: {num(v['up'])} per second\n- Modifiers: {mods(v['mods'])}\n")
    return "\n".join(L)


def events(d):
    L = [GEN, "# World events\n",
         f"{len(d['events'])} events in {len(d['event_cats'])} categories. A random event fires every so often, weighted by `weight` and by the season ([Seasons](civics.md)); you can also trigger them from the World events menu. "
         "`min pop` is the population needed; `duration` is how long the modifiers last; `mods` merge like policy modifiers.\n"]
    for c in d["event_cats"]:
        L.append(f"## {c}\n")
        L.append("| Event | Weight | Min pop | Duration | Modifiers |\n|---|---|---|---|---|")
        its = [(k, v) for k, v in d["events"].items() if v["cat"] == c]
        for k, v in its:
            L.append(f"| [{v['n']}](#{anchor(v['n'])}) | {num(v['w'])} | {num(v['minpop'])} | {num(v.get('dur', 0))} s | {mods(v.get('mods', {}))} |")
        L.append("")
        for k, v in its:
            L.append(f"### {v['n']}\n\nKey `{k}`. {v['desc']}\n")
            extra = []
            if v.get("weather"):
                extra.append(f"Weather: {v['weather']}")
            if v.get("inst"):
                extra.append(f"Instant effect: {mods(v['inst'])}")
            if v.get("scale"):
                extra.append(f"Softened by the `{v['scale']}` stat")
            if v.get("needs") is not None:
                extra.append(f"Requires a {d['ids'][str(int(v['needs']))].replace('_', ' ').lower()}")
            if v.get("cost"):
                extra.append(f"Costs {num(v['cost'])} coins to trigger")
            if v.get("player"):
                extra.append("Player-triggered only")
            if extra:
                L.append("- " + "\n- ".join(extra) + "\n")
            L.append(f"News line: \"{v['msg']}\"\n")
    return "\n".join(L)


def units(d):
    L = [GEN, "# Military units\n",
         f"{len(d['kinds'])} unit types. Damage classes: **soft** (infantry), **armor** (vehicles), **air**, **ship**. The `vs` multipliers scale damage against each class. "
         f"Ranks ({', '.join(d['ranks'])}) are earned by damage dealt (or healed): {', '.join(num(x) for x in d['rank_xp'])}; each rank adds +{pct(d['consts']['rank_dmg'])} damage and +{pct(d['consts']['rank_hp'])} hp. "
         f"The army cap is {d['consts']['army_max']} per town. Speed is pixels per second (32 px = 1 tile); range in pixels. `cap` is how many of the unit each building supports. "
         "See [War and military](war.md) for the rules.\n",
         "| Unit | Class | HP | Damage | Range | Speed | Cost | Upkeep | Train s | Defence weight |\n|---|---|---|---|---|---|---|---|---|---|"]
    for k, v in d["kinds"].items():
        L.append(f"| [{v['n']}](#{anchor(v['n'])}) | {v['t']} | {num(v['hp'])} | {num(v['dmg'])} | {num(v['rng'])} | {num(v['spd'])} | {num(v['cost'])} | {num(v['upk'])} | {num(v['train'])} | {num(d['def_w'].get(k, 0))} |")
    L.append("")
    for k, v in d["kinds"].items():
        L.append(f"## {v['n']}\n\nKey `{k}`, class {v['t']}.\n")
        L.append("- Housed by: " + (", ".join(f"{d['defs'][b]['n']} (up to {c})" for b, c in v["cap"].items()) or "-"))
        if v.get("vs"):
            L.append("- Damage multipliers: " + ", ".join(f"{c} x{num(m)}" for c, m in v["vs"].items()))
        if v.get("heal"):
            L.append(f"- Heals {num(v['heal'])} hp per second in range (no attack)")
        if v.get("lands"):
            L.append(f"- Carries and lands {num(v['lands'])} soldiers")
        if v.get("radar"):
            L.append("- Needs a radar station to fly")
        L.append("")
    return "\n".join(L)


def civics(d):
    c = d["consts"]
    L = [GEN, "# Civics, seasons and progression\n",
         f"A year is {c['year_days']} days (4 seasons x 7). A day is {num(c['day_secs'])} sim seconds. Elections are held at the end of each year.\n", "## Town ranks\n",
         "| Peak population | Rank |\n|---|---|"]
    L += [f"| {a} | {b} |" for a, b in d["city_ranks"]]
    L += ["", "## Seasons\n"]
    for s in d["seasons"]:
        L.append(f"### {s['n']}\n\n{s['txt']}\n\n- Farm harvest multiplier: x{num(s['harvest'])}\n- Modifiers: {mods(s['mods'])}\n- Event weight multipliers: {mods(s['ev'])}\n")
    L += ["## Tribes\n", "Every citizen belongs to one tribe. `share` is the weight in the population mix.\n", "| Tribe | Share | Wants | Content | Unhappy |\n|---|---|---|---|---|"]
    for k, v in d["tribes"].items():
        L.append(f"| {v['n']} (`{k}`) | {v['w']} | {v['wants']} | {v['up']} | {v['down']} |")
    L += ["", "## Petitions\n", "A tribe asks every 70-130 s. `Need` is checked every tick; accepting makes it a promise with a deadline in days. See [Mayor and elections](civics-mechanics.md).\n",
          "| Petition | Tribe | Need | Deadline | Min pop |\n|---|---|---|---|---|"]
    for p in d["petitions"]:
        need = ", ".join(f"{k}: {(d['defs'][str(v)]['n'] if k == 'build' else v)}" for k, v in p["need"].items())
        L.append(f"| {p['t']} (`{p['id']}`) | {d['tribes'][p['tribe']]['n']} | {need} | {p['days']} d | {p.get('minpop', 0)} |")
    L += ["", "## Milestones\n", "| Milestone | Condition | Reward |\n|---|---|---|"]
    L += [f"| {m['n']} | `{m['stat']}` >= {num(m['v'])} | {m['reward']} |" for m in d["milestones"]]
    L += ["", "## Loans\n", "| Loan | Amount | Term | Interest | Min pop |\n|---|---|---|---|---|"]
    L += [f"| {l['n']} | {l['amt']} | {l['days']} d | {pct(l['rate'])} | {l['minpop']} |" for l in d["loans"]]
    L += ["", f"Campaign rally: {num(c['rally_cost'])} coins.\n", "## Diplomacy costs\n", "| Action | Cost |\n|---|---|"]
    L += [f"| {k} | {num(v)} |" for k, v in d["diplo_costs"].items()]
    L += ["", "## Guide steps (first-run tutorial)\n"]
    L += [f"- **{s['t']}**: {s['x']}" for s in d["guide"]]
    return "\n".join(L) + "\n"


def constants(d):
    L = [GEN, "# Tuning constants\n", "The values the rules are built on, read from the code at generation time.\n", "| Constant | Value |\n|---|---|"]
    L += [f"| `{k}` | {json.dumps(v) if isinstance(v, dict) else num(v)} |" for k, v in d["consts"].items()]
    return "\n".join(L) + "\n"


PAGES = {"buildings.md": buildings, "stats.md": stats, "policies.md": policies, "events.md": events, "units.md": units, "civics.md": civics, "constants.md": constants}


def render(dest):
    d = dump()
    dest.mkdir(parents=True, exist_ok=True)
    for name, fn in PAGES.items():
        (dest / name).write_text(fn(d), encoding="utf-8")


if __name__ == "__main__":
    wiki = root / "docs" / "wiki"
    if "--check" in sys.argv:
        tmp = pathlib.Path(tempfile.mkdtemp())
        render(tmp)
        bad = [n for n in PAGES if not (wiki / n).exists() or (wiki / n).read_text() != (tmp / n).read_text()]
        print("WIKI_OK" if not bad else "wiki pages out of date, run python3 scripts/gen_wiki.py: " + ", ".join(bad))
        sys.exit(1 if bad else 0)
    render(wiki)
    print("wrote", ", ".join(PAGES))
